apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuboapp
  labels:
    app: kuboapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuboapp
  template:
    metadata:
      labels:
        app: kuboapp
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
